import DoctorIcon from './icons/DoctorIcon'
import FemaleDoctorIcon from './icons/FemaleDoctorIcon'

export const doctors = [
  {
    id: 'ahmed-khalid',
    name: 'Dr. Ahmed Khalid',
    title: 'BDS, MSc, RCS (Edin)',
    specialty: 'Cosmetic & Restorative Dentistry',
    experience: '20+ Years',
    education: 'King\'s College London, UK',
    certifications: 'UK General Dental Council, DHA Licensed',
    bio: 'Dr. Ahmed is a renowned cosmetic dentist with 20+ years of international experience. Trained in London, now serving Dubai\'s elite with world-class aesthetic dentistry.',
    image: '/images/profile-fb-1480085465-bb6c9de79b16.jpg',
    achievements: 'Over 5,000 smile transformations',
  },
  {
    id: 'fatima-al-rashid',
    name: 'Dr. Fatima Al Rashid',
    title: 'BDS, MSc (Pediatrics)',
    specialty: 'Pediatric Dentistry',
    experience: '15+ Years',
    education: 'University of Pennsylvania, USA',
    certifications: 'American Board of Pediatric Dentistry, DHA Licensed',
    bio: 'Dr. Fatima specializes in pediatric dentistry with extensive training from the US. She creates positive dental experiences for children across the UAE.',
    image: '/images/profile-fb-1502817706-2b51aa841673.jpg',
    achievements: 'Dubai\'s Top Pediatric Dentist 2023',
  },
  {
    id: 'mohammed-hassan',
    name: 'Dr. Mohammed Hassan',
    title: 'BDS, MSc, PhD (Orthodontics)',
    specialty: 'Orthodontics & Dental Implants',
    experience: '18+ Years',
    education: 'Harvard Dental School, USA',
    certifications: 'American Board of Orthodontics, DHA Licensed',
    bio: 'Dr. Hassan is a Harvard-trained orthodontist and implant specialist. He brings cutting-edge orthodontic solutions to Dubai with 18+ years of expertise.',
    image: '/images/profile-fb-1506718363-818e3cb347dc.jpg',
    achievements: 'Published 25+ research papers',
  },
  {
    id: 'noora-saeed',
    name: 'Dr. Noora Saeed',
    title: 'BDS, MSc (Periodontology)',
    specialty: 'Periodontology & Gum Health',
    experience: '12+ Years',
    education: 'University of Toronto, Canada',
    certifications: 'Canadian Board of Periodontology, DHA Licensed',
    bio: 'Dr. Noora is a periodontology expert with Canadian training. She specializes in advanced gum treatments and implant surgery for Dubai residents.',
    image: '/images/profile-fb-1511174309-478bb5fd4b45.jpg',
    achievements: 'Pioneer in laser gum therapy',
  },
]
